### PR TITLE
allow PATCH http method.

### PR DESCRIPTION
**Pull request by adrianiacobghiula**
added in javax.ws.rs-api since 2.1
https://github.com/jax-rs/api/blob/master/jaxrs-api/src/main/java/javax/ws/rs/HttpMethod.java#L91-L93

### CODE REVIEW

**Comment by adrianiacobghiula** [comment]
@freddyboucher @mkristian Would you guys agree that PATCH should be allowed as it is in jax rs 2.1 & the json path  is a complete as https://tools.ietf.org/html/rfc6902

**Comment by freddyboucher** [comment]
@adrianiacobghiula 
It seems good to me but can you add a JUnit test please?
Thankiu

**Comment by adrianiacobghiula** [comment]
Hi @freddyboucher . 
I did create the test - https://github.com/resty-gwt/resty-gwt/compare/master...adrianiacobghiula:feature/patch-unit-test . 
The problem is that the test does not work on gwt 2.7.0 as the PATCH is rejected on the client side . Updating to 2.8.0 the test is successful. 

Upgrading to gwt 2.8.0 makes my test work but a lot of other tests turn red :( . I tried to go that rabbit hole to see how it goes:
- ResteasyGwtJacksonTestGwt -> trying to postThrowable -> not really clear where would this feature be used...but no longer works -> I think GwtJackson generates a UmbrellaExceptionBeanJsonDeserializer that is not even compilable
-  GenericsTestGwt not longer works as the compiler complains that in GenericDTO the T is not used -> which is true -> the example is just bad :( as GenericDTO  is not a generic object
- EncoderDecoderTestGwt fails -> I stopped here
I am not sure how you would like to handle this: upgrading to gwt 2.8.0 is a big thing and requires a lot more effort . I could try to help but collaboration would be required as some features like posting an exception maybe should just be dropped - or dropping support for jdk7

Could we merge this PR and have a new version of resty and tackle the upgrade of gwt in a different pr ?

**Comment by adrianiacobghiula** [comment]
@freddyboucher What is your opinion :D ?

**Pull request closed without merging**
