### PR TITLE
Break up Encode and Decode generated methods into helper methods

### PR DESCRIPTION
**Pull request by el5y**

### CODE REVIEW

**Comment by el5y** [comment]
@mkristian  Added some changes to the JsonEncoderDecoderClassCreator to breakup the encode and decode methods in to smaller helper methods to help avoid the Java method byte limit

**Comment by mkristian** [comment]
@el5y I will have a look - sounds good

**Comment by el5y** [comment]
Not sure why the previous changes that were in master are showing up as changes here. I merged from master into my branch.

**Comment by mkristian** [comment]
@el5y sorry for the delay but your PR was kind of messed up  somehow. I created a new PR with hopefully only your changes in place: #389 
want to see what travis says to it and test it a bit locally. you could have I look if I missed something.

**Comment by el5y** [comment]
@mkristian  I took a look at your new PR and those changes looked ok. Made a comment over there about needing to update the pom.xml files for the examples so they reference the correct version.

**Comment by el5y** [comment]
Closed this since @mkristian put up a cleaner version of this

**Pull request closed without merging**
