### PR TITLE
Update gwt-jackson to 0.15.2 (and jackson to 2.9.5)

### PR DESCRIPTION
**Pull request by freddyboucher**

### CODE REVIEW

**Comment by ggriffithsIDBS** [comment]
@freddyboucher What version of restygwt will be using this version?

**Comment by ggriffithsIDBS** [comment]
@mkristian i saw 2.2.4 was released but the master pom is still 2.2.3? and 2.2.4 doesnt seem to be available on maven?

**Comment by mkristian** [comment]
@ggriffithsIDBS not today though, but tomorrow I have time for it ;)

**Comment by ggriffithsIDBS** [comment]
@mkristian  no rush for us, luckily 2.2.3 has the right version for us as well, we were really out of date! just noticed 2.2.4 existed on git hub, but not on maven repo 👍

**Pull request merged**
