### PR TITLE
Fix for Jersy server array with 1 element and for turn off the 'X-HTTP-Method-Override' header.

### PR DESCRIPTION
**Pull request by frami**
Jersy returns json arrays with only one element as object. I fixed this by trying to get the object and put it into an array.

Also I added an attribut to turn off the 'X-HTTP-Method-Override' header

### CODE REVIEW

**Comment by Armageddon-** [comment]
Thanx. How do you serialize the array?

Would be great if you could add a small test case, especially for the json array part, but also for the #245 solution.

**Comment by frami** [comment]
I added a test for the json array.
I write a frontend for openhab and the rest servlet there returns arrays with one element as object. After some researching I found out, that they use Jersey and it's a known behave.

**Comment by mkristian** [comment]
+1 overall

**Comment by frami** [comment]
I added a comment this morning with the test.
https://github.com/frami/resty-gwt/commit/e61883efa86d8670f01fdba4e3e6cdaf186dd6e9

**Comment by mkristian** [comment]
@frami nice to have those jersey json work now

**Pull request merged**
