### PR TITLE
Fix #254 and some optimization

### LINKED ISSUE #254: Generating *_Generated_RestServiceProxy_.java fails when List<T> is expected from REST service
Hi!

I have the following REST service on my GWT client:
```java
package test.client.gwt.client.service.rest;

import java.util.List;

import javax.ws.rs.Path;
import javax.ws.rs.QueryParam;

import org.fusesource.restygwt.client.JSONP;
import org.fusesource.restygwt.client.MethodCallback;
import org.fusesource.restygwt.client.RestService;

import test.common.dto.User;

public interface UserService extends RestService {

	@Path("http://localhost:8080/test.server.rest/users")
	@JSONP
	void getUserList(
			@QueryParam("offset") Integer offset,
			@QueryParam("limit") Integer limit,
			MethodCallback<List<User>> callback);
}
```

where `User` is defined as

```java
package test.common.dto;

import java.math.BigInteger;

public class User {

	private BigInteger id;

	private String firstName;

	private String secondName;

	public User() {}

	public User(String firstName, String secondName) {
		this.firstName = firstName;
		this.secondName = secondName;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSecondName() {
		return secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	public BigInteger getId() {
		return id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

}
```

When trying to compile my GWT application I get the folliwing error:

```
[INFO] --- gwt-maven-plugin:2.7.0:compile (default) @ test.client.gwt ---
[INFO] Compiling module test.client.gwt.testClientGWT
[INFO]    Adding '2' new generated units
[INFO]       See snapshot: C:\Windows\TEMP\test.client.gwt.client.service.rest.UserService_Generated_RestServiceProxy_7823676910508270362.java
[INFO]       Ignored 1 unit with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    Tracing compile failure path for type 'test.client.gwt.client.service.rest.UserService_Generated_RestServiceProxy_'
[INFO]       [ERROR] Errors in 'C:\Work\test\workspace_4\test.client.gwt\target\.generated\test\client\gwt\client\service\rest\UserService_Generated_RestServiceProxy_.java'
[INFO]          [ERROR] Line 38: The method getJavaScriptObject() is undefined for the type JSONValue
[INFO]    [ERROR] Hint: Check that the type name 'test.client.gwt.client.service.rest.UserService_Generated_RestServiceProxy_' is really what you meant
[INFO]    [ERROR] Hint: Check that your classpath includes all required source roots
[INFO]    [ERROR] Errors in 'test/client/gwt/client/application/userlist/UserListPresenter.java'
[INFO]       [ERROR] Line 27: Rebind result 'test.client.gwt.client.service.rest.UserService_Generated_RestServiceProxy_' could not be found
```

The generated class that have errors looks in this way:
```java
package test.client.gwt.client.service.rest;

public class UserService_Generated_RestServiceProxy_ implements test.client.gwt.client.service.rest.UserService,
		org.fusesource.restygwt.client.RestServiceProxy {
	private org.fusesource.restygwt.client.Resource resource = null;

	@Override
	public void setResource(org.fusesource.restygwt.client.Resource resource) {
		this.resource = resource;
	}

	@Override
	public org.fusesource.restygwt.client.Resource getResource() {
		if (this.resource == null) {
			String serviceRoot = org.fusesource.restygwt.client.Defaults.getServiceRoot();
			this.resource = new org.fusesource.restygwt.client.Resource(serviceRoot);
		}
		return this.resource;
	}

	private org.fusesource.restygwt.client.Dispatcher dispatcher = null;

	@Override
	public void setDispatcher(org.fusesource.restygwt.client.Dispatcher dispatcher) {
		this.dispatcher = dispatcher;
	}

	@Override
	public org.fusesource.restygwt.client.Dispatcher getDispatcher() {
		return this.dispatcher;
	}

	@Override
	public void getUserList(java.lang.Integer offset, java.lang.Integer limit,
			org.fusesource.restygwt.client.MethodCallback<java.util.List<test.common.dto.User>> callback) {
		final java.lang.Integer final_offset = offset;
		final java.lang.Integer final_limit = limit;
		final org.fusesource.restygwt.client.Method __method =
				getResource()
						.resolve("http://localhost:8080/test.server.rest/users")
						.addQueryParam("offset", (offset != null ? offset.toString() : null))
						.addQueryParam("limit", (limit != null ? limit.toString() : null))
						.jsonp();
		__method.setDispatcher(this.dispatcher);
		((org.fusesource.restygwt.client.JsonpMethod) __method)
				.send(new org.fusesource.restygwt.client.AbstractAsyncCallback<java.util.List<test.common.dto.User>>(
						(org.fusesource.restygwt.client.JsonpMethod) __method, callback) {
					@Override
					protected java.util.List<test.common.dto.User> parseResult(
							com.google.gwt.json.client.JSONValue result) throws Exception {
						try {
							result = new com.google.gwt.json.client.JSONArray(result.getJavaScriptObject());
							return org.fusesource.restygwt.client.AbstractJsonEncoderDecoder.toList(result,
									test.common.dto.User_Generated_JsonEncoderDecoder_.INSTANCE);
						} catch (Throwable __e) {
							throw new org.fusesource.restygwt.client.ResponseFormatException(
									"Response was NOT a valid JSON document", __e);
						}
					}
				});
	}
}
```

In maven I'm using the following dependencies:
```xml
        <dependency>
			<groupId>org.fusesource.restygwt</groupId>
			<artifactId>restygwt</artifactId>
			<version>2.0.3</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.bundles</groupId>
			<artifactId>jaxrs-ri</artifactId>
			<version>2.17</version>
		</dependency>
```

I've tried to change `List<User>` to `User`, then it compiles well.

Could you please help me to find an issue or to find a workaround?

Thanks!

### PR DESCRIPTION
**Pull request by Armageddon-**
See issue #254

### CODE REVIEW

**Comment by mkristian** [comment]
@Armageddon- I like your work on resty-gwt so I added you as contributor. please feel free to merge PR as they come in. or directly push your fixes to the repo. thanx all your work so far ;)

**Comment by Armageddon-** [comment]
@mkristian Thank you very much. I hope it's ok, if I close some fixed issues or some there was no update for more than three month.

**Comment by mkristian** [comment]
@Armageddon- that is OK - just keep the ones which do enough info and can be fixed. usually I go through the list before a release ;)

**Comment by Armageddon-** [comment]
@mkristian Ok, thank you. After I merged pull request #259 an build error occur in "restygwt-rails-example" thats not gone after merge my this pull request. It seems to be a problem from travis but I'm not sure. Do you have any idea?

**Comment by mkristian** [comment]
yeah. there were problems with maven repo serving gem artifacts for the
rails application. all good again :)

**Pull request merged**
