### PR TITLE
Feature/cleanup+improvements+add possibility to respect media type annotations

### LINKED ISSUE #113: Unable to handle plain text
Server resource:

```java
@GET
@Path("plaintext")
public String retrievePlainText() {
 return "This is plain text.";
}
```

Client service:

```java
@GET
@Path("plaintext")
public void retrievePlainText(MethodCallback<String> callback);
```
Service call:

```java
myService.retrievePlainText(myCallback);
```

Client output:

```text
[INFO]  - Sending http request: GET http://127.0.0.1:8888/rest/plaintext ,timeout:0
[INFO]  - Received http response for request: GET http://127.0.0.1:8888/rest/plaintext
This is plain text.

[ERROR] - Could not parse response: org.fusesource.restygwt.client.ResponseFormatException: Response was NOT a valid JSON document
```

Add annotation to the client service, call the service again.

```java
@Consumes(MediaType.TEXT_PLAIN)
```

Client output:

```text
[INFO]  - Sending http request: GET http://127.0.0.1:8888/rest/plaintext ,timeout:0
```

Server output:

```text
[WARN] 415 - GET /rest/plaintext (127.0.0.1) 
   Request headers
      ...
      Accept: application/json
      ...
   Response headers
      Content-Type: text/html
      ...
```

### PR DESCRIPTION
**Pull request by Armageddon-**
Add possibility to send String as Json by using @Consumes("application/json") and receive String as text by using @Produces("text/plain").

closes #113

### CODE REVIEW

**Comment by Armageddon-** [comment]
@mkristian Hello, I would not merge without your approval or suggestions for improvement, because it is a huge change.

**Comment by mkristian** [comment]
I had already a brief look at it but realized I need more time. I am on it right now

**Comment by Armageddon-** [comment]
@mkristian thank you for your comments and catching my typo.
I have made the changes according to your comments.

**Comment by mkristian** [comment]
what is the risk to activate this per default ?

**Comment by Armageddon-** [comment]
The risk is that applications could stop working after update to new version because normaly resty using ".text" to send strings.

**Pull request merged**
