### PR TITLE
Fix for #342 - use EncoderDecoderLocator to serialize Date query param

### PR DESCRIPTION
**Pull request by aponyrko**

### CODE REVIEW

**Comment by aponyrko** [comment]
Please let me know if there's a test strategy for the affected class, I took a brief look but did not find a test I could follow as an example.

**Comment by aponyrko** [comment]
Note, I think there's a problem with my current fix where by using the JSON encoder, it adds surrounding double quotes to the formatted date value. I will revisit.

**Comment by freddyboucher** [comment]
@aponyrko 
I was working on the same issue, then I saw your PR.
I implemented a test for your fix https://github.com/resty-gwt/resty-gwt/issues/342

**Comment by mkristian** [comment]
@freddyboucher I just merged this PR and could you submit your tests against master of resty-gwt ?

**Comment by freddyboucher** [comment]
@mkristian 
Done https://github.com/resty-gwt/resty-gwt/pull/346

**Pull request merged**
